### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Glandos** [hfujita/pulseaudio-raop2#1]
First of all, many thanks for your great work.

My home setup involves IPv6 at home. There are currently two issues:
- Two sinks are shown instead of one. I don't know how this could be handled. But they have exactly the same name, this make the second point really hard;
- If I select the IPv6 sink, it fails to connect. I'll explain why further. The biggest problem is that the sink is not cleaned, so that when I try to stop the stream, an assert fails, and Pulseaudio crashes. It make it impossible to revert back to the normal sink.

Why IPv6 connect fails?

The host attribute of the RAOP struct is initialized with the parsed address (using pa_parse_address), that strips the enclosing brackets. However, the RTSP struct is also initialized with the parsed address, and when the RTSP client tries to connect, it tries to reparse the address. This fails with IPv6 addresses. Maybe a good fix should be to store the parsed address inside the RAOP struct and the RTSP struct, instead of reparsing it on each connect. But since I don't know every Pulseaudio internals, I don't want to start messing the code :smile:

**Comment by Glandos** [comment]
Hmm, it seems more complicated than this… The ANNOUNCE command is sending IP4 option with the IPv6 address… I think the IPv4 logic is deep here :wink:

**Comment by hfujita** [comment]
Thank you for reporting the issue. I have to admit that I've never tested the code with IPv6 server addresses. However, fortunately, my device does support IPv6, so I think I can reproduce the issue. I can't make a commitment right now about when the fix will be ready, but if it is ready I'll get back to you.

**Comment by hfujita** [comment]
@Glandos, can I see the results of `avahi-browse -ar`?
I got an Apple TV 3rd gen, and found that the command showed an IPv4 address even for an entry of the IPv6 result.

**Comment by Glandos** [comment]
https://gist.github.com/Glandos/7061201

Sorry for the delay, a new boy has just arrived in my home, it's tiny, but requires a lot of time :smile:

**Comment by hfujita** [comment]
@Glandos Thanks for the log, and congratulations! :) These days I've been a bit busy to work on PulseAudio but I'll keep this in mind.

**Comment by josla972** [comment]
First of all, thank you very much for implementing UDP support! Finally I can stream audio to my raspberry pi without problems.

On topic: I added an ugly fix to remove IPV6 connections: https://github.com/hfujita/pulseaudio-raop2/pull/12

**Comment by hfujita** [comment]
Hi, I've added an experimental IPv6 support in the `hf/raop2-v2-ipv6` branch. Please try it out!

**Comment by Glandos** [comment]
Wow. Impressive. Streaming to Kodi (just updated) works nearly with no delay. I'm able to watch a movie with MPV and the lip sync is nearly perfection. So much work done, it's delightful to enjoy it :)

However, I'm able to see both IPv4 and IPv6 sinks, but for an unknown reason the IPv4 is not working. But since the IPv6 one is OK, I'll close the issue.

Good job!

**Comment by Glandos** [comment]
By the way, do you have an idea when the ipv6 branch could be merged in the current development branch?
