### ISSUE TITLE
Prerequisites missing package

### ISSUE THREAD

**Issue by stephan-henningsen** [hfujita/pulseaudio-raop2#16]
I need to install a last package before being able to build; you should probably add it to your list of 0. Prerequisites =)

sudo apt-get install intltool

I got this error before installing it:

$ cd pulseaudio-raop2/
$ ./autogen.sh 
Activated pre-commit hook.
./bootstrap.sh: line 47: intltoolize: command not found
./autogen.sh: 23: exec: ./configure: not found

**Comment by hfujita** [comment]
Hi, thank you for the suggestion and sorry for late reply. I added intltool to the instraction.

**Comment by jcsid** [comment]
Hi,
I had the same problem and installed intltoolize but still, I get this:

./autogen.sh: 23: exec: ./configure: not found

(On Debian sid)

**Comment by stephan-henningsen** [comment]
Hi,

I don't know if this is the right place, but it's kind of a follow-up.  I've just followed your updated instructions and they're great! Also thanks for credits ;).  A few things missing to make it perfect, though it may be a matter of taste:

A) Disabling autospawn
     Creating missing directory prior to creating file:

```
mkdir ~/.pluse ; echo "autospawn=no" >> ~/.pulse/client.conf
```

B) Configuration file for local devices (for PA 5.0)
  I find the $PA_SRC_DIR a but confusing since it's the only time you mention; the rest of the time you assume people have followed your instructions, thus ./src/modules... should be fine.  It also breaks copy-pasting when you have to edit the command =)

```
cp /usr/share/pulseaudio/alsa-mixer/profile-sets/extra-hdmi.conf \
./src/modules/alsa/mixer/profile-sets/
```

C) Perhaps ditch the $ prompt in all the commands; I perfectly understand why it's there, but without it copy/pasing is a lot easier (triple-click).  Maybe I'm just lazy ;)

Other than that, I can confirm that Spotify (0.9.11.27.g2b1a638.81-1) on Ubuntu 14.04 now plays on our office's BeoPlay A9, so I guess you can add those to your list. Of course I forgot to turn the volume down so I nearly blew a speaker and gave myself and my colleagues a heart attach.  Thanks a lot! ;)

Really, thanks for your great work.  I think this should be merged into Ubuntu so everyone can benefit.
