### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by rainerda** [hfujita/pulseaudio-raop2#25]
Sudden crashes for flash playback to my shairport. Here is some output:

( 454.014| 433.822) D: [raop-sink] raop_client.c: Discarding audio packet 19213 due to EAGAIN
( 454.022|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19214 due to EAGAIN
( 454.038|   0.016) D: [raop-sink] raop_client.c: Discarding audio packet 19216 due to EAGAIN
( 454.046|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19217 due to EAGAIN
( 454.062|   0.016) D: [raop-sink] raop_client.c: Discarding audio packet 19219 due to EAGAIN
( 454.070|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19220 due to EAGAIN
( 454.078|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19221 due to EAGAIN
( 454.094|   0.015) D: [raop-sink] raop_client.c: Discarding audio packet 19223 due to EAGAIN
( 454.102|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19224 due to EAGAIN
( 454.109|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19225 due to EAGAIN
( 454.118|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19226 due to EAGAIN
( 454.126|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19227 due to EAGAIN
( 454.133|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19228 due to EAGAIN
( 454.149|   0.015) D: [raop-sink] raop_client.c: Discarding audio packet 19230 due to EAGAIN
( 454.165|   0.015) D: [raop-sink] raop_client.c: Discarding audio packet 19232 due to EAGAIN
( 454.229|   0.063) D: [raop-sink] raop_client.c: Discarding audio packet 19240 due to EAGAIN
( 454.237|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19241 due to EAGAIN
( 454.245|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19242 due to EAGAIN
( 454.253|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19243 due to EAGAIN
( 454.261|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19244 due to EAGAIN
( 454.269|   0.008) D: [raop-sink] raop_client.c: Discarding audio packet 19245 due to EAGAIN
( 454.277|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19246 due to EAGAIN
( 454.285|   0.007) D: [raop-sink] raop_client.c: Discarding audio packet 19247 due to EAGAIN
( 454.364|   0.078) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.364|   0.000) D: [raop-sink] raop_client.c: Resending 2 packets starting at 19213
( 454.365|   0.000) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.365|   0.000) D: [raop-sink] raop_client.c: Resending 2 packets starting at 19216
( 454.366|   0.000) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.366|   0.000) D: [raop-sink] raop_client.c: Resending 3 packets starting at 19219
( 454.369|   0.002) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.369|   0.000) D: [raop-sink] raop_client.c: Resending 6 packets starting at 19223
( 454.370|   0.001) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.371|   0.000) D: [raop-sink] raop_client.c: Resending 1 packets starting at 19230
( 454.377|   0.006) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.377|   0.000) D: [raop-sink] raop_client.c: Resending 1 packets starting at 19232
( 454.377|   0.000) D: [raop-sink] module-raop-sink.c: Received control packet.
( 454.377|   0.000) D: [raop-sink] raop_client.c: Resending 8 packets starting at 19240
( 455.440|   1.062) D: [raop-sink] module-raop-sink.c: Received control packet.
( 455.440|   0.000) D: [raop-sink] raop_client.c: Resending 1 packets starting at 19214
( 455.440|   0.000) E: [raop-sink] raop_packet_buffer.c: Assertion 'packet->data[4 + 3] == (seq_num & 0xff)' failed at modules/raop/raop_packet_buffer.c:166, function pa_raop_pb_read_packet(). Aborting.
Aborted (core dumped)

drainer@travelmate:~/Downloads/pulseaudio-raop2$ date
Son Nov  9 13:28:53 CET 2014
drainer@travelmate:~/Downloads/pulseaudio-raop2$ git status
On branch hf/raop2-v2
Your branch is up-to-date with 'origin/hf/raop2-v2'.

Thanks for all the work by the way!

**Comment by hfujita** [comment]
I'm wondering if you are using a correct version. When you look at raop-packet-buffer.c, there is no such line 166: https://github.com/hfujita/pulseaudio-raop2/blob/hf/raop2-v2/src/modules/raop/raop-packet-buffer.c

Please do the following steps before we proceed to the next step:
1. show me the result of `git show HEAD --summary`
2. do `git pull`
3. do `make clean && make`

**Comment by rainerda** [comment]
1. do make clean && make
   Bingo!
   I feel super stupid ;-)

**Comment by rainerda** [comment]
Updated and did the build.
I hope I can give some better output now.

(7259.123|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=605) packet due to EAGAIN (Resource temporarily unavailable)
(7259.123|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=606) packet due to EAGAIN (Resource temporarily unavailable)
(7259.123|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=607) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=608) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=609) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=610) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=611) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=612) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=613) packet due to EAGAIN (Resource temporarily unavailable)
(7259.124|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=614) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=615) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=616) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=617) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=618) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=619) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=620) packet due to EAGAIN (Resource temporarily unavailable)
(7259.125|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=621) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=622) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=623) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=624) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=625) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=626) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=627) packet due to EAGAIN (Resource temporarily unavailable)
(7259.126|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=628) packet due to EAGAIN (Resource temporarily unavailable)
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=629) packet due to EAGAIN (Resource temporarily unavailable)
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=630) packet due to EAGAIN (Resource temporarily unavailable)
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=631) packet due to EAGAIN (Resource temporarily unavailable)
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Discarding UDP (audio, seq=632) packet due to EAGAIN (Resource temporarily unavailable)
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Received UDP control packet...
(7259.127|   0.000) D: [raop-sink-[192.168.0.101]:5002] raop-client.c: Resending 677 packets starting at 60422
(7259.127|   0.000) E: [raop-sink-[192.168.0.101]:5002] memblock.c: Assertion 'length' failed at pulsecore/memblock.c:218, function pa_memblock_new(). Aborting.
Aborted (core dumped)
drainer@travelmate:~$ cd Downloads/pulseaudio-raop2/
drainer@travelmate:~/Downloads/pulseaudio-raop2$ git show HEAD --summary
commit 6e38dd77a91bb7be1c722eadf754f3af1f3b0a00
Author: Hajime Fujita crisp.fujita@nifty.com
Date:   Sun Oct 19 00:07:12 2014 -0500

```
raop: Remove redundant initialization code
```

drainer@travelmate:~/Downloads/pulseaudio-raop2$ 

i got this after an hour of playing flacs with clementine on my shairport raspberry pie musicbox. Sounds awesome by the way.

**Comment by hfujita** [comment]
@rainerda Thank you for reporting. The new issue looks quite similar to #23. So from now on I'll discuss this issue in #23.
