### ISSUE TITLE
./configure: not found

### ISSUE THREAD

**Issue by jcsid** [hfujita/pulseaudio-raop2#30]
Hi,

Trying to compile pulseaudio-raop2 on Debian Sid, I get this message:

$ git clone https://github.com/hfujita/pulseaudio-raop2.git
$ cd pulseaudio-raop2/
$ ./autogen.sh 
./autogen.sh: 23: exec: ./configure: not found

Regards,
JC

**Comment by hfujita** [comment]
Didn't you see any other message from ./autogen.sh?

**Comment by jcsid** [comment]
I just forgot the apt-get dep part. Sorry

**Comment by fire-fly** [comment]
Hi there,
I had the same error running on OS X 10.10.1.
Follow the instruction on http://www.freedesktop.org/wiki/Software/PulseAudio/Ports/OSX/
I new to OS X.
The error was "./autogen.sh: line 23: /Users/xxx/Downloads/pulseaudio/configure: No such file or directory"

Thanks
Please help.

**Comment by fire-fly** [comment]
Hi
above problem "./autogen.sh: line 23: /Users/xxx/Downloads/pulseaudio/configure: No such file or directory" resolved, after installing pkg-config.

But new problem. The error was
pulse/channelmap.c:27:10: fatal error: 'stdlib.h' file not found
#include <stdlib.h>

All  standard hearders were not in /usr/include
