### ISSUE TITLE
problem with module-detect

### ISSUE THREAD

**Issue by fugazy** [hfujita/pulseaudio-raop2#33]
hello, 
i try to use pulseaudio-raop2 to use freebox revolution airplay as a audio output od my raspbian raspeberryPI

I try a lot off thing but i'm stuck with that message 
(   0.128|   0.000) E: [lt-pulseaudio] module.c: Failed to load module "module-detect" (argument: ""): initialization failed.
(   0.129|   0.001) E: [lt-pulseaudio] main.c: Module load failed.

can you help me ?

here the complete log : 
(   0.000|   0.000) W: [lt-pulseaudio] main.c: Le programme n'est pas conçu pour être lancé en tant que root (sauf si --system est renseigné).
(   0.002|   0.002) D: [lt-pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
(   0.003|   0.001) D: [lt-pulseaudio] core-util.c: setpriority() worked.
(   0.004|   0.001) I: [lt-pulseaudio] core-util.c: Successfully gained nice level -11.
(   0.005|   0.001) I: [lt-pulseaudio] main.c: This is PulseAudio 5.99.1-60-g4f5a0
(   0.006|   0.000) D: [lt-pulseaudio] main.c: Compilation host: armv6l-unknown-linux-gnueabihf
(   0.007|   0.000) D: [lt-pulseaudio] main.c: Compilation CFLAGS:  -g -O0 -Wall -W -Wextra -pipe -Wno-long-long -Wno-overlength-strings -Wunsafe-loop-optimizations -Wundef -Wformat=2 -Wlogical-op -Wsign-compare -Wformat-security -Wmissing-include-dirs -Wformat-nonliteral -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wmissing-prototypes -Wredundant-decls -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wendif-labels -Wcast-align -Wstrict-aliasing -Wwrite-strings -Wno-unused-parameter -ffast-math -fno-common -fdiagnostics-show-option
(   0.008|   0.001) D: [lt-pulseaudio] main.c: Running on host: Linux armv6l 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014
(   0.009|   0.001) D: [lt-pulseaudio] main.c: Found 1 CPUs.
(   0.010|   0.000) I: [lt-pulseaudio] main.c: Page size is 4096 bytes
(   0.011|   0.000) D: [lt-pulseaudio] main.c: Compiled with Valgrind support: no
(   0.012|   0.000) D: [lt-pulseaudio] main.c: Running in valgrind mode: no
(   0.013|   0.000) D: [lt-pulseaudio] main.c: Running in VM: no
(   0.013|   0.000) D: [lt-pulseaudio] main.c: Optimized build: no
(   0.013|   0.000) D: [lt-pulseaudio] main.c: All asserts enabled.
(   0.014|   0.001) I: [lt-pulseaudio] main.c: Machine ID is d3670ff77a0bb988a953e7f053a3f4e7.
(   0.016|   0.002) I: [lt-pulseaudio] main.c: Using runtime directory /root/.pulse/d3670ff77a0bb988a953e7f053a3f4e7-runtime.
(   0.017|   0.000) I: [lt-pulseaudio] main.c: Using state directory /root/.pulse.
(   0.017|   0.000) I: [lt-pulseaudio] main.c: Using modules directory /home/pi/pulseaudio-raop2/src/.
(   0.017|   0.000) I: [lt-pulseaudio] main.c: Running in system mode: no
(   0.022|   0.004) I: [lt-pulseaudio] main.c: Fresh high-resolution timers available! Bon appetit!
(   0.027|   0.005) D: [lt-pulseaudio] memblock.c: Using shared memory pool with 1024 slots of size 64,0 Kio each, total size is 64,0 Mio, maximum usable slot size is 65496
(   0.032|   0.004) D: [lt-pulseaudio] memblock.c: Using shared memory pool with 1024 slots of size 64,0 Kio each, total size is 64,0 Mio, maximum usable slot size is 65496
(   0.036|   0.004) I: [lt-pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP 
(   0.037|   0.001) I: [lt-pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
(   0.041|   0.003) D: [lt-pulseaudio] cli-command.c: Parsing script '/home/pi/pulseaudio-raop2/src/default.pa'
(   0.059|   0.018) I: [lt-pulseaudio] module-device-restore.c: Successfully opened database file '/root/.pulse/d3670ff77a0bb988a953e7f053a3f4e7-device-volumes'.
(   0.060|   0.001) I: [lt-pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
(   0.074|   0.014) I: [lt-pulseaudio] module-stream-restore.c: Successfully opened database file '/root/.pulse/d3670ff77a0bb988a953e7f053a3f4e7-stream-volumes'.
(   0.076|   0.001) I: [lt-pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
(   0.088|   0.011) I: [lt-pulseaudio] module-card-restore.c: Successfully opened database file '/root/.pulse/d3670ff77a0bb988a953e7f053a3f4e7-card-database'.
(   0.089|   0.001) I: [lt-pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
(   0.100|   0.010) I: [lt-pulseaudio] module.c: Loaded "module-augment-properties" (index: #3; argument: "").
(   0.111|   0.010) I: [lt-pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #4; argument: "").
(   0.113|   0.002) D: [lt-pulseaudio] module.c: Checking for existence of '/home/pi/pulseaudio-raop2/src/module-detect.so': failure
(   0.114|   0.001) D: [lt-pulseaudio] module.c: Checking for existence of '/home/pi/pulseaudio-raop2/src/.libs/module-detect.so': success
(   0.124|   0.009) W: [lt-pulseaudio] module.c: module-detect is deprecated: Please use module-udev-detect instead of module-detect!
(   0.127|   0.002) W: [lt-pulseaudio] module-detect.c: failed to detect any sound hardware.
(   0.128|   0.000) E: [lt-pulseaudio] module.c: Failed to load module "module-detect" (argument: ""): initialization failed.
(   0.129|   0.001) E: [lt-pulseaudio] main.c: Module load failed.
(   0.130|   0.000) E: [lt-pulseaudio] main.c: Échec lors de l'initialisation du démon
(   0.131|   0.001) I: [lt-pulseaudio] module.c: Unloading "module-switch-on-port-available" (index: #4).
(   0.132|   0.001) I: [lt-pulseaudio] module.c: Unloaded "module-switch-on-port-available" (index: #4).
(   0.133|   0.000) D: [lt-pulseaudio] core-subscribe.c: Dropped redundant event due to remove event.
(   0.134|   0.000) I: [lt-pulseaudio] module.c: Unloading "module-augment-properties" (index: #3).
(   0.135|   0.001) I: [lt-pulseaudio] module.c: Unloaded "module-augment-properties" (index: #3).
(   0.136|   0.000) D: [lt-pulseaudio] core-subscribe.c: Dropped redundant event due to remove event.
(   0.137|   0.000) I: [lt-pulseaudio] module.c: Unloading "module-card-restore" (index: #2).
(   0.139|   0.001) I: [lt-pulseaudio] module.c: Unloaded "module-card-restore" (index: #2).
(   0.139|   0.000) D: [lt-pulseaudio] core-subscribe.c: Dropped redundant event due to remove event.
(   0.140|   0.000) I: [lt-pulseaudio] module.c: Unloading "module-stream-restore" (index: #1).
(   0.142|   0.002) I: [lt-pulseaudio] module.c: Unloaded "module-stream-restore" (index: #1).
(   0.142|   0.000) D: [lt-pulseaudio] core-subscribe.c: Dropped redundant event due to remove event.
(   0.142|   0.000) I: [lt-pulseaudio] module.c: Unloading "module-device-restore" (index: #0).
(   0.144|   0.001) I: [lt-pulseaudio] module.c: Unloaded "module-device-restore" (index: #0).
(   0.144|   0.000) D: [lt-pulseaudio] core-subscribe.c: Dropped redundant event due to remove event.
(   0.146|   0.002) I: [lt-pulseaudio] main.c: Daemon terminated.

**Comment by fugazy** [comment]
resolve this with enable udev

**Comment by gianarb** [comment]
Hello I have the same problem but I don't have the udev module in my system. I compiled the current master.

**Comment by noamelf** [comment]
Helped me as well... Thanks!
