### ISSUE TITLE
PulseAudio now at version 9

### ISSUE THREAD

**Issue by francoisjacques** [hfujita/pulseaudio-raop2#59]
The project appears unmaintained at this point... unless a fork is maintained? (EDIT: found mikkeloscar/pulseaudio-raop2 fork, looks slightly more maintained)

It was promising. I'm still hoping this will get eventually leave the experimental stage and get merged into PulseAudio main trunk; this would allow a second life to many deprecated AirPort Express units.

**Comment by piit79** [comment]
Wtf, version 9?! I see they must have switched to the now-popular Firefox/Chrome version numbering ;)

On a more related note, I would also love to see pulseaudio-raop2 merged into mainline pulseaudio. I wonder if we could help somehow?

**Comment by hfujita** [comment]
Hey, thank you for your comment. I've been trying to push it to mainline but haven't successful so far. I'm not sure how much it helps but if you would like it to be merged please leave your comments for support.

**Comment by cadesalaberry** [comment]
Nice, I would also like it to be merged.

**Comment by francoisjacques** [comment]
For those who wish to try it, should we be using https://github.com/mikkeloscar/pulseaudio-raop2 instead of this repo?

**Comment by atcapollo** [comment]
How do you get it merged into mainline? I'd like to see this merged. I
assume it is not as simple as pushing a commit.

On 5 Oct 2016 18:44, "François Jacques" notifications@github.com wrote:

For those who wish to try it, should we be using https://github.com/
mikkeloscar/pulseaudio-raop2 instead of this repo?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/hfujita/pulseaudio-raop2/issues/59#issuecomment-251746559,
or mute the thread

**Comment by hfujita** [comment]
@francoisjacques either way. Seems like it's a rebase on newer PulseAudio. If you're interested on trying it out on the latest source, I can rebase my patches on top of it.

@atcapollo In order to get it merged to the mainline, I need to convince PulseAudio maintainers to do so.

**Comment by cadesalaberry** [comment]
@hfujita It would be great if you could !

**Comment by francoisjacques** [comment]
@hfujita looking at the changes... the change for solaris/openindiana could be sent independently. Small fixes are easier to get through, incrementally.

**Comment by francoisjacques** [comment]
@hfujita I don't know enough about pulseaudio to have an opinion on the changes in pulse/pulsecore. I would expect that's where you might get the most comments. 

For the changes in raop itself... I wonder if there might be concerns about introducing regression in the current raop module. Although I don't think the current raop implementation is hardly useful to anyone. Perhaps discuss the matter with pulseaudio maintainers if they'd rather have an raop2 module side-by-side? This would make it easier to get it merged as it won't cause side-effect on the old implementation, and possible uses. Kinda sucks to have both though.

**Comment by Toby-Haynes** [comment]
I would also like to see this merged in PulseAudio mainline. 

@hfujita: what were the objects raised by the pulseaudio team? Too big? Not reviewed? I've been running this code for a couple of years or more now without obvious issues, for my Logitech UE Air speaker. Understanding what obstacles we need to overcome to get this integrated will help.

**Comment by hfujita** [comment]
In my understanding, the biggest issue is that the core maintainers of PA do not have enough bandwidth to review all patches, and obviously raop support is not the highest priority thing for the PulseAudio project (which is unfortunate, but understandable.) Actually there are many outstanding patches waiting for review over years, other than the raop ones. Another issue I know of is that the current code doesn't work for the latest Apple TV (Gen4; with Siri.) That was pointed out by a reviewer but I'm not sure it's a critical blocker for merging.

@francoisjacques solaris/openindiana? I'm sorry, which part are you talking about?
Regarding having separate raop/raop2 code, actually when I started working on this project the code was separate. Later, Martin Blanchard and I agreed to merge these two codes for better maintainability. Either way has its own pros/cons so we cannot say which is the right way to do it. Anyway, so far that has never been an issue during conversation with PA maintainers.

**Comment by francoisjacques** [comment]
@hfujita (solaris) my bad. module-solaris.c showed up in a diff between your branch and upstream, but I think the branch simply needs to be rebased again.

For the pulseaudio 'core' being overwhelmed. This is understandable; many patches from various Linux distros and other platforms!

🤔 

(Haven't done the aforementioned rebase yet... thinking out loud on the internets... might be irrelevant, perhaps already tried...)

_If_ there are any changes _outside_ of raop module, these could be pushed separately and would be easier for the core team to review and approve. Perhaps there isn't any of such changes, though.

If there was an agreement to have both raop modules merged - awesome! Makes it simpler for users too :-)

Afterwards, with backing from respected sponsors, all the changes to raop can be proposed to the core and being all concentrated in one area, that would make it less stressful to un-stabilize the main tree. With references to popular tickets in the main distros, even better!

That being written, I think an important concern for them might the support of these changes once they are merged, should there be regressions. The target audience will become larger...

I think having a perfect patch that supports all iDevices is a bit irrelevant. The current raop implementation is really limited. Any patch that adds the support for even just one iDevice should be welcome. With no support from Apple (for understandable commercial reason) PulseAudio will always be behind by a few iDevices generations.

**Comment by hfujita** [comment]
Yeah I did also try to submit (some, not all) small patches that touch outside of the raop module, which did not success either. Anyway I think the patches are already small enough so it should be easy to segregate commits that touches outside of the module. And I believe these numbers are small.

Anyway, as PA 9.0 just came out, now it may be a good time to try this again, with some more open discussion on how we can proceed on this.

**Comment by Toby-Haynes** [comment]
I think this project is suitably advanced, useful and stable to be included in the pulseaudio code base. When you do post for inclusion, I'll try to support your cause!

**Comment by hfujita** [comment]
Just started a discussion at pulseaudio-discuss. Will see what'll happen this time.

**Comment by mrlnc** [comment]
For those watching the github issue but not pulseaudio-discuss: [Weblink to pulseaudio-discuss thread](https://lists.freedesktop.org/archives/pulseaudio-discuss/2016-October/thread.html#27009)

**Comment by hfujita** [comment]
Finally some support patches were merged to the "next" branch!
https://lists.freedesktop.org/archives/pulseaudio-discuss/2016-October/027035.html

To be clear, the rest of the patches that actually implements raop2 features are not yet merged. However, I think this is a very important step. Anyone who can comment on the rest of the code (on the mailing list) will be welcome.

**Comment by francoisjacques** [comment]
Woohoo! That's great news @hfujita! Thank you so much!

**Comment by hfujita** [comment]
Great news folks!
Finally all the raop2 patches were merged into the `next` branch, which means I guess, they are likely to be in the 11.0 release! (Now 10.0 is in the final preparation, so let's wait for one more cycle.)
https://lists.freedesktop.org/archives/pulseaudio-discuss/2017-January/027362.html

Patches in the `next` branch: https://cgit.freedesktop.org/pulseaudio/pulseaudio/log/?h=next

Thank you everyone for your support and feedback! I'm thrilled to see more usecases and feedbacks once it's released.

**Comment by piit79** [comment]
That's awesome, @hfujita! Thanks a lot for not giving up. It was great to see things start moving at last not too long ago (when some of the support patches were merged), I wasn't really expecting the rest to be merged this quickly :)
Can't wait to be able to use my AVR out of the box in the next Kubuntu release ;)
Thanks again! :+1:

**Comment by francoisjacques** [comment]
Thank you @hfujita ! Great work! I'll look forward trying it as soon as PA11 becomes available! Given the higher frequency of PA releases, I think the wait shouldn't be too long? :crossed_fingers:

**Comment by cadesalaberry** [comment]
Thanks a lot @hfujita for your persistence !!! Can't wait for it to be released !!!

**Comment by hfujita** [comment]
@francoisjacques Recently it seems that PulseAudio has been released twice a year. https://www.freedesktop.org/wiki/Software/PulseAudio/
So I'd guess 11.0 will come out sometime around mid-late 2017.

**Comment by francoisjacques** [comment]
@hfujita thanks for the info! I'll check how to to build it locally then (funtoo linux) I also have a few annoyances with my external USB sound device which I'd like to investigate and - hopefully - fix.

**Comment by Glandos** [comment]
Pulseaudio 11 has been released, with this marvelous work merged.
Many congratulations to @hfujita for his perseverance. This was a long path, but I think it is worthy for many users.

**Comment by sonvirgo** [comment]
Please commit back the patch for openssl1.1.0 as upstream raop2 module is not reliable.

**Comment by hfujita** [comment]
@sonvirgo Which patch?

**Comment by sonvirgo** [comment]
@hfujita https://lists.freedesktop.org/archives/pulseaudio-discuss/2017-January/027349.html

**Comment by hfujita** [comment]
@sonvirgo it's already merged to upstream.

**Comment by hfujita** [comment]
@sonvirgo Oh, do you mean porting that patch back to one of the branches here? Since all patches were merged to upstream, I'm no longer maintaining these branches.
What's the issue with PA 11.1? Maybe you can report it to pulseaudio-discuss mailing list.

**Comment by sonvirgo** [comment]
I am trying to build it for Ubuntu 17.04 but it seems tedious

**Comment by Glandos** [comment]
@hfujita Maybe you can write this in the project description and at the top of the README:

> This project was merged upstream in version X.Y, so it is no longer maintained. Please report all bug in upstream at http://…
