### ISSUE TITLE
why??

### ISSUE THREAD

**Issue by alanchang15** [hfujita/pulseaudio-raop2#66]
modules/raop/raop-crypto.c:72:8: error：dereferencing pointer to incomplete type 「RSA {aka struct rsa_st}」
     rsa->n = BN_bin2bn(modules, size, NULL);
        ^~

**Comment by sonvirgo** [comment]
openssl1.1.0 change API
I have tested upstream pulseaudio 11.1 but raop2 module is not reliable

**Comment by hfujita** [comment]
@alanchang15 Are you using a branch from this repository? raop2 has been merged to upstream. Please use the upstream PulseAudio.
