### ISSUE TITLE
compile for raspberry

### ISSUE THREAD

**Issue by bendschs** [hfujita/pulseaudio-raop2#70]
compile the package for raspberry. i am using https://github.com/osmc/osmc which is based on deibian stretch. failed at compiling raop2. would be nice if you could provide an apt-get package soon!

b

**Comment by piit79** [comment]
Please note the raop2 patches have been merged into upstream PulseAudio 11.0, so you should just try to build the upstream version or find a package of PA 11.0+ for Debian Stretch. Please close this issue.

**Comment by bendschs** [comment]
was able to compile a PA 11 on stretch
