### ISSUE TITLE
Make fails on Kali Kernel 5.7.0

### ISSUE THREAD

**Issue by davidganz** [hfujita/pulseaudio-raop2#75]
**Trace**:
pulsecore/shm.c:199:25: warning: taking address of packed member of ‘struct shm_marker’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  199 |         pa_atomic_store(&marker->marker, SHM_MARKER);
      |                         ^~~~~~~~~~~~~~~
pulsecore/shm.c: In function ‘pa_shm_cleanup’:
pulsecore/shm.c:466:28: warning: taking address of packed member of ‘struct shm_marker’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  466 |         if (pa_atomic_load(&m->marker) != SHM_MARKER) {
      |                            ^~~~~~~~~~
pulsecore/shm.c:471:44: warning: taking address of packed member of ‘struct shm_marker’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  471 |         if (!(pid = (pid_t) pa_atomic_load(&m->pid))) {
      |                                            ^~~~~~~
make[3]: *** [Makefile:8452: pulsecore/libpulsecommon_7.0_la-shm.lo] Error 1
make[3]: Leaving directory '/home/magcig/Downloads/pulseaudio-raop2/src'
make[2]: *** [Makefile:5318: all] Error 2
make[2]: Leaving directory '/home/magcig/Downloads/pulseaudio-raop2/src'
make[1]: *** [Makefile:807: all-recursive] Error 1
make[1]: Leaving directory '/home/magcig/Downloads/pulseaudio-raop2'
make: *** [Makefile:622: all] Error 2

**Comment by hfujita** [comment]
This tree is no longer maintained as the feature has been already merge to upstream PulseAudio. Please try the [latest PulseAudio release](https://www.freedesktop.org/wiki/Software/PulseAudio/Download/).
