### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by singpolyma** [hfujita/pulseaudio-raop2#9]
When I try to play with sox's play command, or when I stop VLC playback, when connected to my RAOP device I get `(  55.179|   0.000) E: [raop-sink] rtsp_client.c: Assertion 'c->url' failed at modules/rtp/rtsp_client.c:406, function rtsp_exec(). Aborting.` and then pulseaudio stops.

**Comment by josla972** [comment]
Same here.

**Comment by singpolyma** [comment]
Don't know if it's right, but the following fixes the crash:

```
-    if (c->rtsp != NULL) {
+    if (c->rtsp != NULL && pa_rtsp_exec_ready(c->rtsp)) {
```

**Comment by atcapollo** [comment]
Where does this fix get made? I do not see 

if (c->rtsp != NULL) { 

in rtsp_client.c

**Comment by singpolyma** [comment]
@atcapollo https://github.com/hfujita/pulseaudio-raop2/blob/raop2-for-merge2/src/modules/raop/raop_client.c#L1150

**Comment by atcapollo** [comment]
Seems to run move the issue.

**Comment by hfujita** [comment]
Hi, thank you for your contribution and sorry for the delay in response.
I slightly reformatted your patch and pushed it to hf/raop2-v2 branch. I'd happy if you could confirm that the patch fixes your issue.

**Comment by hfujita** [comment]
I assume this has been fixed... if not please reopen (can you? not sure if Github allows it) or post a new issue. Thanks.
